### ISSUE TITLE
Searchbar Should work.

### ISSUE THREAD

**Issue by devharsh007** [devharsh007/Web_city#8]
Write a proper script for search bar working,  which should be used for searching the  website.

**Comment by SAHIL-KUMAR-EE** [comment]
Hello,
I can try to implement the search bar. Kindly assign this issue to me

**Comment by HTQun** [comment]
Hi, you can assign for me?

**Comment by devharsh007** [comment]
Sure @SAHIL-KUMAR-EE  as u requested first. you can work on it. @HTQun you also do it  and  can do check other issues too ...
If you have any websites which are worth adding in this list please do add in JSON file. (issue no #11 )

**Comment by devharsh007** [comment]
@HTQun , @SAHIL-KUMAR-EE  can u work on issue #7  as i was unable to do it. If u found any enhancements, do tell me.

**Comment by devharsh007** [comment]
@HTQun , @SAHIL-KUMAR-EE  can u work on issue #7  as i was unable to do it. If u found any enhancements, do tell me.

**Comment by nguyenthihuynhgiao** [comment]
Hi, Can I work them

**Comment by devharsh007** [comment]
> Hi, Can I work them

About this issue.. a PR is pending, but other issues.. Sure 😃 man. @nguyenthihuynhgiao
